services:
  api:
    build:
      context: .
      dockerfile: MicroServ01.Api/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__dbMicro01=Server=127.0.0.1;Port=3306;Database=${MYSQL_DATABASE};User=root;Password=${MYSQL_ROOT_PASSWORD};
#     depends_on:
#       - db

#   db:
#     image: mysql:8.0
#     container_name: mysql-container
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_DATABASE: ${MYSQL_DATABASE}
#     ports:
#       - "3306:3306"
#     volumes:
#       - db_data:/var/lib/mysql
#       - ./db:/docker-entrypoint-initdb.d

# volumes:
#   db_data: